apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-indoorcup-ddnss
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-indoorcup-ddnss
            image: busybox
            args:
            - /bin/sh
            - curl -X GET 'https://ddnss.de/upd.php?key=$SECRET_DDNSS_KEY&host=indoorcup.ddnss.org'
            env:
            - name: SECRET_DDNSS_KEY
              valueFrom:
                secretKeyRef:
                  name: ddnss-key
                  key: key
          restartPolicy: OnFailure
